title: "Muhammad Zeeshan Arshad"
description: "R&D Software Engineer at Advantest Europe GmbH"
show_downloads: false
theme: jekyll-theme-slate
lang: "en"

author: 
    name: "Muhammad Zeeshan Arshad"
    email: "zeeshan.arshad@tum.de"
    url: "https://zsnzeeshan.github.io"

# Social profiles (used for JSON-LD)
social:
  name: "Muhammad Zeeshan Arshad"
  links:
    - https://github.com/ZsnZeeshan
    - https://www.linkedin.com/in/muhammad-zeeshan-arshad/
    - https://orcid.org/0009-0000-6227-8153