version: "3.8"

services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: jekyll
    command: jekyll serve --watch --force_polling --host 0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - ./:/srv/jekyll

  cibuild:
    image: jekyll/jekyll:latest
    container_name: cibuild
    working_dir: /srv/jekyll
    volumes:
      - ./:/srv/jekyll
    tty: true
    command: bash -c "bundle install && ./script/cibuild"
    
###################################################
# first time setup
###################################################
# docker compose run jekyll bundle add github-pages
# docker compose run jekyll bundle install
# docker compose up
# then open http://localhost:4000 in your browser

###################################################